### ISSUE TITLE
Is there any API references or examples?

### ISSUE THREAD

**Issue by deskl0** [monoxide13/Arduino_SBUS#1]

**Comment by monoxide13** [comment]
I'll try and dig up something from my old programs and see what I've got.

**Comment by monoxide13** [comment]
I used this to control some 2812 LEDs on my RC plane. I also included a LCD library for testing to see what output values were coming out of the SBUS. It's not necessary for the operation but I left it in for debugging abilities.
```
/*
 * 
 * Values from SBUS input 0%-100% correlate to 172-1811.
 * FRSKY reciever ouput is 1000 to 2000 us.
 * 
 */



//#define USELCD
#define USE2812

#include <SBUS.h>
#include <Servo.h>
#include <Wire.h>
#ifdef USELCD
#include <LiquidCrystal_I2C.h>
LiquidCrystal_I2C lcd(0x20,16,2);
#endif
#ifdef USE2812
#include <FastLED.h> 
#endif
#define NUM_LEDS 45
#define FASTLED_BUILTIN 12
#define RSSI_MAX 90
#define RSSI_MIN 50

const int navLightPin = 5;
const int landingLightPin = 3;
const int rssiPin = 0; // A0
CRGB fastLedPtr[NUM_LEDS];
const int leftWingLeds = 15;
CRGB * leftWingPtr = fastLedPtr;
const int rightWingLeds = 15;
CRGB * rightWingPtr = leftWingPtr + leftWingLeds;
const int boomLeds = 11;
CRGB * boomPtr = rightWingPtr + rightWingLeds;
const int tailLeds = 4;
CRGB * tailPtr = boomPtr + boomLeds;
int maxIn = 600, minIn = 600;
unsigned int chanValue=600, errors=0;
unsigned long lastPacket = 0, currentTime=0, failsafeTime=0, updateTime=0;
unsigned int brightness=30;
short flightMode=0, oldMode=1;
bool failsafeBool=false, failsafeToggle=false;
bool updateLights=true;
bool shiftLights=false;
unsigned int sequence=0;
unsigned long sequenceTime=0;
CRGB navLightPtr[NUM_LEDS];

ArduinoSBUS* sbus = new ArduinoSBUS();
Servo outServo;

void setup() {
  // put your setup code here, to run once:
  sbus->begin(Serial, false, 98500); //100,000 is actual, but people have found 97000 to 99000 is more stable.
  sbus->attachDataReceived(newSBUSdata);
  sbus->attachFrameError(newFrameError);
  outServo.attach(9, 1200, 1800);
  pinMode(LED_BUILTIN, OUTPUT);
  //pinMode(navLightPin, OUTPUT);
  pinMode(landingLightPin, OUTPUT);
  #ifdef USELCD
  lcd.init();
  lcd.noCursor();
  lcd.noBlink();
  lcd.clear();
  lcd.backlight();
  lcd.print("Starting");
  #endif
  FastLED.addLeds<WS2812, FASTLED_BUILTIN, GRB>(fastLedPtr, NUM_LEDS);
  //FastLED.setDither(0);
  int x;
  for(x=0; x<leftWingLeds; ++x)
    leftWingPtr[x]=CRGB::Red;
  for(x=0; x<rightWingLeds; ++x)
    rightWingPtr[x]=CRGB::Green;
  for(x=0; x<boomLeds+tailLeds; ++x)
    boomPtr[x]=CRGB::White;
  memcpy(navLightPtr, fastLedPtr, sizeof(CRGB)* NUM_LEDS);
  delay(100);
  for(x=0;x<20;++x){
    FastLED.showColor(CRGB::White, 20); delay(100);
    FastLED.showColor(CRGB::Black, 255); delay(100);
  }
}

void loop() {
  currentTime=millis(); // Because nothing here requires exact timing, it's more effiecent to only save millis() once.
    //analogRead(rssiPin);
  #ifdef USELCD
    lcd.clear();
    lcd.home();
    lcd.print(minIn);
    lcd.print("-");
    lcd.print(maxIn);
    //lcd.setCursor(0,1);
    //lcd.print(errors);
  #endif

  sbus->receive();
  if(currentTime>updateTime){
    updateTime=currentTime+100; // Update every 1/10th of a second.
    if(lastPacket+2000<currentTime){
      flightMode=0;
      failsafeBool=false;
    }
    switch(flightMode){
      case 0:
        oldMode=0;
        if(failsafeBool && currentTime>failsafeTime){
        // Fail safe is set. Flash lights.
          failsafeTime=currentTime+200;
          if(failsafeToggle=!failsafeToggle){ // FAILSAFE
            analogWrite(landingLightPin, 100);
            FastLED.showColor(CRGB::Black, 255);
          }else{
            analogWrite(landingLightPin, 0);
            FastLED.showColor(CRGB::Red, 40);
          }
        }else if(!failsafeBool && currentTime>failsafeTime){ // NOT RECEIVING PACKETS
          failsafeTime=currentTime+200;
          if(failsafeToggle=!failsafeToggle){
            analogWrite(landingLightPin, 100);
            FastLED.showColor(CRGB::Black, 255);
          }else{
            analogWrite(landingLightPin, 0);
            FastLED.showColor(CRGB::Purple, 70);
          }
        }
        break;
      case 1: // nav/orientation lights.
        if(oldMode!=1){
          memcpy(fastLedPtr, navLightPtr, sizeof(CRGB)*NUM_LEDS);
          oldMode=1;
        }else{
          analogWrite(landingLightPin, brightness);
          //FastLED.show(brightness);
          FastLED.show(brightness);
        }
        break;
      case 2: // rssi/bat status.
        if(oldMode!=2){
          sequence=0;
          sequenceTime=currentTime;
          oldMode=2;
        }
        {
          fastLedPtr[sequence]=CRGB::White;
          if(sequence==0)
            fastLedPtr[NUM_LEDS-1]=CRGB::Black;
          else
            fastLedPtr[sequence-1]=CRGB::Black;
          if(++sequence==NUM_LEDS)
            sequence=0;
            FastLED.show(brightness);
        }
        break;
      case 3: // fun 1 lights.
        if(oldMode!=3){
          shiftLights=true;
          sequence=0;
          oldMode=3;
        }
        {
          if(sequence!=15){
            rightWingPtr[sequence]=CRGB::Red;
            rightWingPtr[(-1)-sequence]=CRGB::Red;
            boomPtr[sequence]=CRGB::Red;
            }
          if(sequence!=0){
              rightWingPtr[sequence-1]=CRGB::Black;
              rightWingPtr[-sequence]=CRGB::Black;
              boomPtr[sequence-1]=CRGB::Black;
          }
          if(++sequence==16) // 15 leds, last sequence all black.
            sequence=0;
          FastLED.show(brightness);
          }
          /*
          fastLedPtr[sequence]=CRGB::White;
          if(sequence==0)
            fastLedPtr[NUM_LEDS-1]=CRGB::Black;
          else
            fastLedPtr[sequence-1]=CRGB::Black;


            */
        break;
      case 4: // fun lights.
        break;
      default:
        break;
    }
  }
}

void newSBUSdata(ChannelData data){
  // Data 6 passes brightness values. Data 7 passes mode.
  brightness=map(data.data[6], 172, 1811, 0, 255);
  if(failsafeBool=sbus->getFailSafe()){
    flightMode=0;
  }else if(data.data[7]<600)
    flightMode=1;
  else if(data.data[7]<1500)
    flightMode=2;
  else
    flightMode=3;
  digitalWrite(LED_BUILTIN, HIGH); // Only useful when debugging.
  lastPacket=millis();
}

void newFrameError(){
  digitalWrite(LED_BUILTIN, LOW);
}
```

**Comment by deskl0** [comment]
Thank you very much


Sent from my iPhone

On Apr 23, 2020, at 12:01, monoxide13 <notifications@github.com> wrote:

﻿

I used this to control some 2812 LEDs on my RC plane. I also included a LCD library for testing to see what output values were coming out of the SBUS. It's not necessary for the operation but I left it in for debugging abilities.

/*
 *
 * Values from SBUS input 0%-100% correlate to 172-1811.
 * FRSKY reciever ouput is 1000 to 2000 us.
 *
 */



//#define USELCD
#define USE2812

#include <SBUS.h>
#include <Servo.h>
#include <Wire.h>
#ifdef USELCD
#include <LiquidCrystal_I2C.h>
LiquidCrystal_I2C lcd(0x20,16,2);
#endif
#ifdef USE2812
#include <FastLED.h>
#endif
#define NUM_LEDS 45
#define FASTLED_BUILTIN 12
#define RSSI_MAX 90
#define RSSI_MIN 50

const int navLightPin = 5;
const int landingLightPin = 3;
const int rssiPin = 0; // A0
CRGB fastLedPtr[NUM_LEDS];
const int leftWingLeds = 15;
CRGB * leftWingPtr = fastLedPtr;
const int rightWingLeds = 15;
CRGB * rightWingPtr = leftWingPtr + leftWingLeds;
const int boomLeds = 11;
CRGB * boomPtr = rightWingPtr + rightWingLeds;
const int tailLeds = 4;
CRGB * tailPtr = boomPtr + boomLeds;
int maxIn = 600, minIn = 600;
unsigned int chanValue=600, errors=0;
unsigned long lastPacket = 0, currentTime=0, failsafeTime=0, updateTime=0;
unsigned int brightness=30;
short flightMode=0, oldMode=1;
bool failsafeBool=false, failsafeToggle=false;
bool updateLights=true;
bool shiftLights=false;
unsigned int sequence=0;
unsigned long sequenceTime=0;
CRGB navLightPtr[NUM_LEDS];

ArduinoSBUS* sbus = new ArduinoSBUS();
Servo outServo;

void setup() {
  // put your setup code here, to run once:
  sbus->begin(Serial, false, 98500); //100,000 is actual, but people have found 97000 to 99000 is more stable.
  sbus->attachDataReceived(newSBUSdata);
  sbus->attachFrameError(newFrameError);
  outServo.attach(9, 1200, 1800);
  pinMode(LED_BUILTIN, OUTPUT);
  //pinMode(navLightPin, OUTPUT);
  pinMode(landingLightPin, OUTPUT);
  #ifdef USELCD
  lcd.init();
  lcd.noCursor();
  lcd.noBlink();
  lcd.clear();
  lcd.backlight();
  lcd.print("Starting");
  #endif
  FastLED.addLeds<WS2812, FASTLED_BUILTIN, GRB>(fastLedPtr, NUM_LEDS);
  //FastLED.setDither(0);
  int x;
  for(x=0; x<leftWingLeds; ++x)
    leftWingPtr[x]=CRGB::Red;
  for(x=0; x<rightWingLeds; ++x)
    rightWingPtr[x]=CRGB::Green;
  for(x=0; x<boomLeds+tailLeds; ++x)
    boomPtr[x]=CRGB::White;
  memcpy(navLightPtr, fastLedPtr, sizeof(CRGB)* NUM_LEDS);
  delay(100);
  for(x=0;x<20;++x){
    FastLED.showColor(CRGB::White, 20); delay(100);
    FastLED.showColor(CRGB::Black, 255); delay(100);
  }
}

void loop() {
  currentTime=millis(); // Because nothing here requires exact timing, it's more effiecent to only save millis() once.
    //analogRead(rssiPin);
  #ifdef USELCD
    lcd.clear();
    lcd.home();
    lcd.print(minIn);
    lcd.print("-");
    lcd.print(maxIn);
    //lcd.setCursor(0,1);
    //lcd.print(errors);
  #endif

  sbus->receive();
  if(currentTime>updateTime){
    updateTime=currentTime+100; // Update every 1/10th of a second.
    if(lastPacket+2000<currentTime){
      flightMode=0;
      failsafeBool=false;
    }
    switch(flightMode){
      case 0:
        oldMode=0;
        if(failsafeBool && currentTime>failsafeTime){
        // Fail safe is set. Flash lights.
          failsafeTime=currentTime+200;
          if(failsafeToggle=!failsafeToggle){ // FAILSAFE
            analogWrite(landingLightPin, 100);
            FastLED.showColor(CRGB::Black, 255);
          }else{
            analogWrite(landingLightPin, 0);
            FastLED.showColor(CRGB::Red, 40);
          }
        }else if(!failsafeBool && currentTime>failsafeTime){ // NOT RECEIVING PACKETS
          failsafeTime=currentTime+200;
          if(failsafeToggle=!failsafeToggle){
            analogWrite(landingLightPin, 100);
            FastLED.showColor(CRGB::Black, 255);
          }else{
            analogWrite(landingLightPin, 0);
            FastLED.showColor(CRGB::Purple, 70);
          }
        }
        break;
      case 1: // nav/orientation lights.
        if(oldMode!=1){
          memcpy(fastLedPtr, navLightPtr, sizeof(CRGB)*NUM_LEDS);
          oldMode=1;
        }else{
          analogWrite(landingLightPin, brightness);
          //FastLED.show(brightness);
          FastLED.show(brightness);
        }
        break;
      case 2: // rssi/bat status.
        if(oldMode!=2){
          sequence=0;
          sequenceTime=currentTime;
          oldMode=2;
        }
        {
          fastLedPtr[sequence]=CRGB::White;
          if(sequence==0)
            fastLedPtr[NUM_LEDS-1]=CRGB::Black;
          else
            fastLedPtr[sequence-1]=CRGB::Black;
          if(++sequence==NUM_LEDS)
            sequence=0;
            FastLED.show(brightness);
        }
        break;
      case 3: // fun 1 lights.
        if(oldMode!=3){
          shiftLights=true;
          sequence=0;
          oldMode=3;
        }
        {
          if(sequence!=15){
            rightWingPtr[sequence]=CRGB::Red;
            rightWingPtr[(-1)-sequence]=CRGB::Red;
            boomPtr[sequence]=CRGB::Red;
            }
          if(sequence!=0){
              rightWingPtr[sequence-1]=CRGB::Black;
              rightWingPtr[-sequence]=CRGB::Black;
              boomPtr[sequence-1]=CRGB::Black;
          }
          if(++sequence==16) // 15 leds, last sequence all black.
            sequence=0;
          FastLED.show(brightness);
          }
          /*
          fastLedPtr[sequence]=CRGB::White;
          if(sequence==0)
            fastLedPtr[NUM_LEDS-1]=CRGB::Black;
          else
            fastLedPtr[sequence-1]=CRGB::Black;


            */
        break;
      case 4: // fun lights.
        break;
      default:
        break;
    }
  }
}

void newSBUSdata(ChannelData data){
  // Data 6 passes brightness values. Data 7 passes mode.
  brightness=map(data.data[6], 172, 1811, 0, 255);
  if(failsafeBool=sbus->getFailSafe()){
    flightMode=0;
  }else if(data.data[7]<600)
    flightMode=1;
  else if(data.data[7]<1500)
    flightMode=2;
  else
    flightMode=3;
  digitalWrite(LED_BUILTIN, HIGH); // Only useful when debugging.
  lastPacket=millis();
}

void newFrameError(){
  digitalWrite(LED_BUILTIN, LOW);
}
